In [5]:
import pandas as pd
import numpy as np
from joblib import dump,load
from scipy.special import inv_boxcox
lr=load(r"C:\Users\Piyush\Documents\ML\Hands on model\LinearReg_car.joblib")

In [24]:
new_data=pd.DataFrame({"Enginesize":[2],
                       "priceinthousands":[12],
                       "fuelefficiency":[30],
                      "vehicletypepassenger":[1]})

In [25]:
new_data

Enginesize  priceinthousands  fuelefficiency  vehicletypepassenger
0           2                12              30                     1

In [28]:
lr.predict(new_data) ##this is on transformed value

C:\Users\Piyush\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Enginesize
- fuelefficiency
- priceinthousands
- vehicletypepassenger
Feature names seen at fit time, yet now missing:
- Engine_size
- Fuel_efficiency
- Price_in_thousands
- Vehicle_type_Passenger

  warnings.warn(message, FutureWarning)


array([6.3683673])

In [29]:
inv_boxcox(lr.predict(new_data),0.19511845998877894) 

C:\Users\Piyush\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Enginesize
- fuelefficiency
- priceinthousands
- vehicletypepassenger
Feature names seen at fit time, yet now missing:
- Engine_size
- Fuel_efficiency
- Price_in_thousands
- Vehicle_type_Passenger

  warnings.warn(message, FutureWarning)


array([62.75110184])

In [47]:
## we can predict the sales by many specificagtion at time
new_data=pd.DataFrame({"Enginesize":[2,1.8],
                       "priceinthousands":[12,12],
                       "fuelefficiency":[30,28],
                      "vehicletypepassenger":[1,1]})

In [48]:
inv_boxcox(lr.predict(new_data),0.19511845998877894)

C:\Users\Piyush\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Enginesize
- fuelefficiency
- priceinthousands
- vehicletypepassenger
Feature names seen at fit time, yet now missing:
- Engine_size
- Fuel_efficiency
- Price_in_thousands
- Vehicle_type_Passenger

  warnings.warn(message, FutureWarning)


array([62.75110184, 42.94757601])

In [46]:
lr.predict(new_data)

C:\Users\Piyush\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Enginesize
- fuelefficiency
- priceinthousands
- vehicletypepassenger
Feature names seen at fit time, yet now missing:
- Engine_size
- Fuel_efficiency
- Price_in_thousands
- Vehicle_type_Passenger

  warnings.warn(message, FutureWarning)


array([6.3683673 , 4.57428208])